# Configuration for Travis (https://travis-ci.org)

language: objective-c

xcode_workspace: OneTimePassword.xcworkspace
xcode_scheme: OneTimePassword (iOS)

osx_image: xcode8.2

env:
  - RUNTIME="iOS 8.1"  DEVICE="iPad 2"
  - RUNTIME="iOS 8.2"  DEVICE="iPhone 4s"
  - RUNTIME="iOS 8.3"  DEVICE="iPhone 5"
  - RUNTIME="iOS 8.4"  DEVICE="iPhone 5s"
  - RUNTIME="iOS 9.0"  DEVICE="iPhone 6"
  - RUNTIME="iOS 9.1"  DEVICE="iPhone 6 Plus"
  - RUNTIME="iOS 9.2"  DEVICE="iPhone 6s"
  - RUNTIME="iOS 9.3"  DEVICE="iPhone 6s Plus"
  - RUNTIME="iOS 10.0" DEVICE="iPhone SE"
  - RUNTIME="iOS 10.1" DEVICE="iPhone 7"
  - RUNTIME="iOS 10.2" DEVICE="iPhone 7 Plus"

# Include builds for watchOS
matrix:
  include:
    - xcode_scheme: OneTimePassword (watchOS)
      env: BUILD_ONLY="YES" RUNTIME="watchOS 3.1" DEVICE="Apple Watch Series 2 - 42mm"
    - xcode_scheme: OneTimePassword (watchOS)
      env: BUILD_ONLY="YES" RUNTIME="watchOS 2.0" DEVICE="Apple Watch - 38mm"

# Check out nested dependencies
before_install: git submodule update --init --recursive

before_script:
  - DEVICE_ID=com.apple.CoreSimulator.SimDeviceType.$(echo $DEVICE | sed -E -e "s/[ \-]+/ /g" -e "s/[^[:alnum:]]/-/g")
  - RUNTIME_ID=com.apple.CoreSimulator.SimRuntime.$(echo $RUNTIME | sed -E -e "s/[ \-]+/ /g" -e "s/[^[:alnum:]]/-/g")
  - DESTINATION_ID=$(xcrun simctl create Travis $DEVICE_ID $RUNTIME_ID)
  - xcrun simctl boot $DESTINATION_ID
  - if [[ $BUILD_ONLY == YES ]]; then ACTIONS="build"; else ACTIONS="build test"; fi
  - echo "xcodebuild -workspace \"$TRAVIS_XCODE_WORKSPACE\" -scheme \"$TRAVIS_XCODE_SCHEME\" -destination \"id=$DESTINATION_ID\" $ACTIONS"

script: set -o pipefail && xcodebuild -workspace "$TRAVIS_XCODE_WORKSPACE" -scheme "$TRAVIS_XCODE_SCHEME" -destination "id=$DESTINATION_ID" $ACTIONS | xcpretty -c

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
